export const CHANGE_EDUCATION = 'CHANGE_EDUCATION';

export const CHANGE_WORK = 'CHANGE_WORK';

export const CHANGE_PROJECTS = 'CHANGE_PROJECTS';

export const CHANGE_ACTIVITIES = 'CHANGE_ACTIVITIES';

export const CHANGE_LOGIN = 'CHANGE_LOGIN';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';

export const POPUP_LOGIN = 'POPUP_LOGIN';

export const POPUP_REGISTER = 'POPUP_REGISTER';

export const POPUP_LOGIN_CLOSE = 'POPUP_LOGIN_CLOSE';

export const POPUP_REGISTER_CLOSE = 'POPUP_REGISTER_CLOSE';

export const LOGIN_SWITCH = 'LOGIN_SWITCH';

export const REGISTER_SWITCH = 'REGISTER_SWITCH';
